baseURL = "https://greycode.top/"
languageCode = "en-us"
title = "Greycode's Blog"
theme = "cactus"
googleAnalytics = "G-JVLPYZM5G1"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4



[params]
    mainSection = "golang"
    showAllPostsOnHomePage = true

    showProjectsList = true

    copyright = "greycode"

    rss = true
    showAllPostsArchive = true

    description = "Hello,I‘m Greycode. Please use Chrome to browse this site for a better experience."

    colortheme = "white" # dark, light, white, or classic

[[params.social]]
  name = "rss"
  link = "/index.xml"
[[params.social]]
  name = "email"
  link = "zhengminghui99@gmail.com"
[[params.social]]
  name = "github"
  link = "https://github.com/greycodee"

[markup]
# 代码高亮
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "paraiso-light"
    #style = "github"
    tabWidth = 4