# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: hugo Auto

on:
  push:
    branches: [hugo]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Config Git
      run: |
        touch ~/.git-credentials
        echo https://${{ secrets.GIT_NAME }}:${{ secrets.TOKEN }}@github.com >> ~/.git-credentials
        cat ~/.git-credentials
        git config --global credential.helper store
        git config --global user.email "zhengminghui99@gmail.com"
        git config --global user.name "greycodee"
    - name: Install Hexo
      run: |
        npm install
        npm install hexo-cli -g
        npm install hexo-deployer-git -g
        npm install hexo-wordcount -g
        npm install hexo-generator-json-content -g
        npm install hexo-generator-feed -g
        npm install hexo-generator-sitemap -g
        npm install hexo-generator-baidu-sitemap -g
        npm install hexo-baidu-url-submit -g
        npm install hexo-translate-title -g
        npm install hexo-neat -g
        npm install hexo-math -g
    - name: Deploy
      run: |
        rm -rf .deploy_git
        git submodule init themes/vexo
        git submodule update
        hexo clean  
        hexo g -d
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: |
          git submodule init themes/cactus
          git submodule update
          hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public